version: '3.7'

services:
  db:
    container_name: my-sql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: full-cycle
    networks:
      - nginx-net

  app:
    depends_on: 
      - db
    restart: always
    entrypoint: ["./wait-for-it.sh", "db:3306", "--timeout=80", "--", "sh", "-c", "npm install && node server.js"]
    container_name: node-app
    build: ./app/
    networks:
      - nginx-net
    volumes:
      - "./app/src/:/usr/src/app"

  nginx:
    restart: always
    container_name: nginx-server
    build: ./nginx/
    networks:
      - nginx-net
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  nginx-net:
    name: nginx-net
    driver: bridge

volumes:
  db_data:
